### ISSUE TITLE
Improve slicing and flattening of vtkExplicitStructuredGrid along polyline

### ISSUE THREAD

**Issue by HansKallekleiv** [equinor/webviz#137]
https://github.com/equinor/webviz/pull/136 has a very shaky implementation of slicing and flattening a vtk grid along a polyline.

Main issues:
- Slow
- Works incorrectly for curved/irregular polylines. Gives unwanted cell connections
- Poor visualization. Matplotlib image => Plotly

Investigate:
- Possibility with vtk to only work on relevant grid cells instead of slicing the full grid along multiple planes?
- Treat each plane individually instead of combining into a single polydata. Transform each plane along a cumulative x-axis. i.e. distance along polyline.
- Use c code instead of python for performance
- Investigate visualization options, Try for deckgl. Alternatively esv-intersection. Others?

**Comment by anders-kiaer** [comment]
We now use ResInsight instead of VTK.
