### ISSUE TITLE
Make it possible for modules to use app global colors for plots

### ISSUE THREAD

**Issue by anders-kiaer** [equinor/webviz#194]
Current use cases:

- color for sensitivity groups in an ensemble (to distinguish from other sensitivities)
- color for ensemble as a whole (to distinguish from other ensembles)

**Comment by rubenthoms** [comment]
Start with implementing two color ramps at workbench session level:

- One for categorical values
- One for floating values

Default color ramps are hard-coded by default but can be adjusted by user.

**Comment by anders-kiaer** [comment]
Done
