### ISSUE TITLE
Possibility to choose if grouped on ensemble or vector in simulation time series

### ISSUE THREAD

**Issue by anders-kiaer** [equinor/webviz#211]
From https://webviz-subsurface-example.azurewebsites.net/simulation-time-series:
![image](https://github.com/equinor/webviz/assets/31612826/2175ca14-f66e-47f2-9f80-1826cadfd28c)

**Comment by jorgenherje** [comment]
Note:

Consider following options:
- No Grouping (all traces in one plot)
- Time Series (Subplot per time series/vector)
- Ensemble (Subplot per ensemble)
