### ISSUE TITLE
Volumetrics modules - Distribution

### ISSUE THREAD

**Issue by HansKallekleiv** [equinor/webviz#273]
Add first tab of existing volumetrics plugin as multiple modules
    (https://webviz-subsurface-example.azurewebsites.net/volumetrics)
    Ideas for multiple modules:

    1. Generic multi-ensemble plotter with histogram/bar, scatter/distribution, box/violin and table
    
![image](https://github.com/equinor/webviz/assets/16436291/8a948d8e-fdee-4d83-9b39-5cae5e83b605)

    2. Curated plot for zone/region/facies/license. Could be done by having an "aggregate by" selection in the first module?
    
![image](https://github.com/equinor/webviz/assets/16436291/c8312009-e90a-48cc-90de-6020de96cd55)

    3. Convergence plot for single-ensemble
    
![image](https://github.com/equinor/webviz/assets/16436291/6e438ee0-c14b-46fd-869d-09558ce107a6)

**Comment by anders-kiaer** [comment]
Done
