### ISSUE TITLE
Parameter distribution module

### ISSUE THREAD

**Issue by HansKallekleiv** [equinor/webviz#275]
Similar to the first tab of the ParameterAnalysis plugin
https://webviz-subsurface-example.azurewebsites.net/parameter-analysis

Compare and rank parameter distributions in two ensembles.

![image](https://github.com/equinor/webviz/assets/16436291/7c712e46-96a6-4551-b6bb-a0a518bd0c0f)

**Comment by anders-kiaer** [comment]
Done
