### ISSUE TITLE
Issue with `ColorScale.getColorForValue()` when `min === max`

### ISSUE THREAD

**Issue by jorgenherje** [equinor/webviz#303]
When `min === max` the color scale is not able to call `ColorScale.getColorForValue()` without crash. 

The `ColorScale.getColorForValue()`-method calls `ColorPalette.getInterpolatedColor(normalizedValue)` which throws the error.

Seems like the interpolation does not handle min equal max, and this provides error when coloring by parameters. Both when calling `ColorScale.getColorForValue()` directly and `ColorScale.getAsPlotlyColorScaleMarkerObject()`. 

Note: Only tested with `ColorScaleType.Continuous`

---
An example with test data contains parameters where min == max, and the following gives issue:

![image](https://github.com/equinor/webviz/assets/82032112/cbbad2a6-2dee-4037-a394-5dce09e16c28)

**Comment by rubenthoms** [comment]
Fixed by #304.
