### ISSUE TITLE
Change from dynamically to statically created preview SVGs

### ISSUE THREAD

**Issue by anders-kiaer** [equinor/webviz#339]
Currently we create preview SVGs as React components, e.g. https://github.com/equinor/webviz/blob/main/frontend/src/modules/DistributionPlot/preview.tsx.

Should we instead create preview pictures as static SVGs? 

**Benefits:**
- Less JavaScript code (they are SVG pictures instead).
- Less computation needed by browser on resizing settings tab width (it will instead scale the SVG picture accordingly).
- Easier to make complex SVGs probably (as you do not need to code them, and can instead use e.g. Inkscape to create them interactively).

**Downside:** 
- If we at some point want the content to be dynamic, we will not be able to do that easily since it is not a function creating the SVG anymore.

**Comment by rubenthoms** [comment]
We do need a React component anyways. However, the `DrawPreviewFunc` requires only to return a `ReactNode`. Therefore, it is already possible to just return a "pre-drawn" SVG by e.g. writing:

```typescript
import { DrawPreviewFunc } from "@framework/Preview";
import { BarChart } from "@mui/icons-material";

export const preview: DrawPreviewFunc = function (width: number, height: number) {
    return <BarChart style={{ width, height }} />;
};
```

![image](https://github.com/equinor/webviz/assets/69145689/5d31d412-542a-4e83-b206-fc9afc7b41c5)
