### ISSUE TITLE
Fix bug when selecting multiple ensembles with same name SimulationTimeSeriesMatrix

### ISSUE THREAD

**Issue by jorgenherje** [equinor/webviz#341]
The plots are built only using ensemble name for labeling, thus two ensembles with same name from two different cases are placed under the same legend tag and with same color in plot.

Use case name + ensemble name for subplot builder?

--- 

Suggestions: Propagate a display name i VectorSpec, or retrieve info from `Ensemble`-object in view before creating plot builder?

**Comment by anders-kiaer** [comment]
Do we know that "case name + ensemble" is unique? Or can that also be the same for two ensembles (e.g. from different assets)? Should we include the responsibility of creating unique display names to the app global ensemble selector?

**Comment by HansKallekleiv** [comment]
Case name will not be unique, but `case_uuid` will.

**Comment by jorgenherje** [comment]
Sound good. The idea is to fix up to get a legend per unique ensemble selected. I can create a legendgroup with `"ensemble + case uuid"`, and have a display name e.g: `"ensemble + case name"`? As of now I do not know if there is a better way to distinguish the selected ensembles in a better way for disaplay - as `uuid` is not something we want to display?

**Comment by jorgenherje** [comment]
Todo:

- Consider instead of having an empty plot as default, change the default plot title to e.g. "Select a vector to visualize"
- Consider collapsing some of the settings to highlight the important bit. E.g. keep ensembles and vector selection open, but collapse the others.
- Create mapper for `ensembleIdent` to a display name (helper class to provide to subplotBuilder)
   - Can for now provide `"ensemble+case name"`, but can be enriched with alias or additional info in future
- Create mapper for `vectorName` to a display name (helper class to provide to subplotBuilder)
   -  Can for now look up in hard coded file as (copy equivalent to a common util space?): https://github.com/equinor/webviz/blob/main/frontend/src/lib/components/VectorSelector/private-assets/vectorDefinitions.ts

**Comment by rubenthoms** [comment]
Consider moving complex code out of render return and into a function:
```typescript
{visualizationMode === VisualizationMode.STATISTICAL_FANCHART ||
                            (visualizationMode === VisualizationMode.INDIVIDUAL_REALIZATIONS &&
                                prevVisualizationMode === VisualizationMode.STATISTICAL_FANCHART)
                                ? Object.values(FanchartStatisticOption).map((value: FanchartStatisticOption) => {
                                      return (
                                          <Checkbox
                                              key={value}
                                              label={FanchartStatisticOptionEnumToStringMapping[value]}
                                              checked={statisticsSelection?.FanchartStatisticsSelection?.includes(
                                                  value
                                              )}
                                              onChange={(event) => {
                                                  handleFanchartStatisticsSelectionChange(event, value);
                                              }}
                                          />
                                      );
                                  })
                                : Object.values(StatisticFunction_api).map((value: StatisticFunction_api) => {
                                      return (
                                          <Checkbox
                                              key={value}
                                              label={StatisticFunctionEnumToStringMapping[value]}
                                              checked={statisticsSelection?.IndividualStatisticsSelection.includes(
                                                  value
                                              )}
                                              onChange={(event) => {
                                                  handleIndividualStatisticsSelectionChange(event, value);
                                              }}
                                          />
                                      );
                                  })}
```
