### ISSUE TITLE
Global filtering of realizations in the different ensembles

### ISSUE THREAD

**Issue by anders-kiaer** [equinor/webviz#348]
- Ensure consistent filtering across modules (i.e. if I select a subset of realizations for a given ensemble, these are refltected throughout).
- Does grouping of realization in "mini-ensembles"/sensitivities belong here? Or maybe it is better handled in ensemble selector?
- Realization selections should be possible in different ways:
   - Select subset of realization indices directly.
   - Select ranges of parameters for a given ensemble, and calculate the subset of realizations on behalf of the user.

**Comment by jorgenherje** [comment]
Will resolve: https://github.com/equinor/webviz/issues/330
