### ISSUE TITLE
Establish storage account and make available through volumeMounts/blobfuse

### ISSUE THREAD

**Issue by sigurdp** [equinor/webviz#437]
Establish a storage account and make available through volumeMounts/blobfuse so we can get some hands-on experience with the behavior and performance this solution.

It is very likely we need to persist some of the data downloaded from Sumo, either directly or in a transformed format.
For large data, redis or other in-memory caching schemes are probably not viable. We should investigate using disk/files for this type of caching. 

One way of doing this is just utilizing the local disk on the Radix node, but it is unclear whether that is "good form"

Another is to try and utilize volumeMounts, but we need to get a feeling for the performance and limitations of this solution

**Comment by anders-kiaer** [comment]
Closed with #442.
