### ISSUE TITLE
How to handle field specific data/settings that is/are not/will not be in Sumo and is/are currently blocking

### ISSUE THREAD

**Issue by rubenthoms** [equinor/webviz#535]
### Details
- [ ] Name mappings
    - `eclipse2rms`
    - `faultpolygons2surface`
    - `fipnum2regions`
- [ ] Color tables and ranges
- Is currently blocking: 
    - Surface Matrix
    - RFT (missing link to official well name)

### Depends on
- [ ] Nothing

**Comment by anders-kiaer** [comment]
Moved into #555 and #556.
