### ISSUE TITLE
More informative error message on data load failure when possible

### ISSUE THREAD

**Issue by anders-kiaer** [equinor/webviz#643]
![image](https://github.com/equinor/webviz/assets/31612826/a3c07aa9-a3b1-404e-8060-1a42baa0d9b2)

Probably related to missing data in SUMO, but difficult for user to know if it is missing data, or something non-data related failed in backend.

**Comment by anders-kiaer** [comment]
Similar example with PVT: 
![image](https://github.com/equinor/webviz/assets/31612826/e19dd9e4-5bae-452b-9c47-2ee388cfe3e7)

**Comment by anders-kiaer** [comment]
Flow network:


![Image](https://github.com/equinor/webviz/assets/31612826/c449fa7f-6756-440a-ac19-3230610ae507)

**Comment by rubenthoms** [comment]
Mostly implemented in #663. Some backend/frontend error messages might need to be improved but the general framework is implemented.
