### ISSUE TITLE
Remaining tasks `InplaceVolumetrics`

### ISSUE THREAD

**Issue by rubenthoms** [equinor/webviz#688]
### Jørgen
- [x] Select which statistics to show in table
- [x] Result*s* and grouping - consider changing title?
- [x] Change settings order (Place ensemble selection on top?  I.e. refactor `InplaceVolumetricsFilterComponent`)
- [x] Make sure we're using intersections of tables/fluid zones/identifiers
- [x] Refactor settings/view component code to new structure with atoms for business-code
- [x] Box plot should be shown below each other
- [x] Mapping of all table headings to human-readable strings
- [x] Mapping of results to human-readable strings
- [x] Testing of modules
   - Multiple tables -> empty arrays of zone, region and facies -> error in back-end in row filtering algorithm. pc.is_in fails
- [x] Fix column width in statistical table
- [x] Calculate properties after aggregation based on group by identifiers. Calculated properties seems to grow. 
   - E.g. SW and PORO should be a fraction [0,1], but seems to increase based when few groups are selected. To test: group on region, zone, facies, thereafter remove grouping and see fractions increase.
- [x] Aggregation back-end. How to handle calculated properties where a realization value is `inf`? Dash: `np.nanpercentiles`, seems to neglect values equal to `np.nan`. Handle `np.inf` as `np.nan` and neglect nan in calc of statistics (e.g. mask nan-values in pa.array)?
- [x] Replace usage of pyarrow Table in assembler and utils code with `Polars`
- [x] Provide `STOIIP_TOTAL` and `GIIP_TOTAL`
- [x] Debounce selection
    - **NOTES**:
       - Discussed: await/cancel/delay the query/request rather than settings?
       - Debounce per `Select` in `InplaceVolumetricsFilterComponent` gives round trip issues. E.g. selection in one select will override new selections in a second select if the second is modified before timer of first is done. I.e. the second selector has an internal state, but its debounce timer is running before updating its `onChange`. When the first selector timer is done, the props are updated after the round trip. This implies that `value` of all selector-components are updated, and the second selector is "reset" due to update of its value prop.
       - Consider a timer on the `onChange`
       - How to handle synched settings? Also needed to be handled after timer is out?
- [x] Add result columns in table in same order as result names are listed in results select-component in settings
- [x] As back-end has soft fail on data fetching, it can miss some of the requested results. Consider adding warning front-end if retrieved data does not contain requested results. E.g. using statusWriter
- [x] Unit tests for statistics backend - make sure numbers we're presenting are correct
- [x] Handle number of significant decimals of numbers in table. Some numbers might need more than 2 decimals
### Ruben

- [x] Error when selecting simgrid and geogrid for Drogon. Identifier filters disappear for simgrid?
- [x] Result names in order by priority
- [x] When selecting new table, default have all identifiers selected in select object.
- [x] Fix table component to show rows of same height and rather increase total width and fixed header (see #687)
- [x] Show table horizontal scrollbar at bottom

## Back-end
 - [ ] Identifier values should be ordered based on the index in the raw table. Especially important for zones(stratigraphy)

**Comment by HansKallekleiv** [comment]
https://github.com/equinor/webviz-subsurface/blob/master/webviz_subsurface/_abbreviations/abbreviation_data/volume_terminology.json
Prioritized sorting:
1. Stoiip/Giip
2. Other volumetric responses
3. Calculated attributes

E.g.
```
{
  "STOIIP_OIL": {"label": "Stock tank oil initially in place (oil zone)", "unit": "Sm³", "eclsum": ["FOIPL", "ROIPL"]},
  "STOIIP_GAS": {"label": "Stock tank oil initially in place (gas zone)", "unit": "Sm³", "eclsum": ["FOIPG", "ROIPG"]},
  "STOIIP_TOTAL": {"label": "Stock tank oil initially in place (total)", "unit": "Sm³", "eclsum": ["FOIP", "ROIP"]},
  "GIIP_OIL": {"label": "Gas initially in place (oil zone)", "unit": "Sm³", "eclsum": ["FGIPL", "RGIPL"]},
  "GIIP_GAS": {"label": "Gas initially in place (gas zone)", "unit": "Sm³", "eclsum": ["FGIPG", "RGIPG"]},
  "GIIP_TOTAL": {"label": "Gas initially in place (total)", "unit": "Sm³", "eclsum": ["FGIP", "RGIP"]},
  "ASSOCIATEDGAS": {"label": "Associated gas", "unit": "Sm³"},
  "ASSOCIATEDOIL": {"label": "Associated oil", "unit": "Sm³"},
 // "RECOVERABLE_OIL": {"label": "Recoverable volume (oil zone)", "unit": "Sm³"},
 // "RECOVERABLE_GAS": {"label": "Recoverable volume (gas zone)", "unit": "Sm³"},
//  "RECOVERABLE_TOTAL": {"label": "Recoverable volume (total)", "unit": "Sm³"},
  "BULK_OIL": {"label": "Bulk volume (oil zone)", "unit": "m³"},
  "BULK_GAS": {"label": "Bulk volume (gas zone)", "unit": "m³"},
  "BULK_TOTAL": {"label": "Bulk volume (total)", "unit": "m³"},
  "NET_OIL": {"label": "Net volume (oil zone)", "unit": "m³"},
  "NET_GAS": {"label": "Net volume (gas zone)", "unit": "m³"},
  "NET_TOTAL": {"label": "Net volume (total)", "unit": "m³"},
  "PORV_OIL": {"label": "Pore volume (oil zone)", "unit": "m³"},
  "PORV_GAS": {"label": "Pore volume (gas zone)", "unit": "m³"},
  "PORV_TOTAL": {"label": "Pore volume (total)", "unit": "m³"},
  "PORE_OIL": {"label": "Pore volume (oil zone)", "unit": "m³"},
  "PORE_GAS": {"label": "Pore volume (gas zone)", "unit": "m³"},
  "PORE_TOTAL": {"label": "Pore volume (total)", "unit": "m³"},
  "HCPV_OIL": {"label": "Hydro carbon pore volume (oil zone)", "unit": "m³"},
  "HCPV_GAS": {"label": "Hydro carbon pore volume (gas zone)", "unit": "m³"},
  "HCPV_TOTAL": {"label": "Hydro carbon pore volume (total zone)", "unit": "m³"},
  "BULK": {"label": "Bulk volume", "unit": "m³"},
  "NET": {"label": "Net volume", "unit": "m³"},
  "PORV": {"label": "Pore volume", "unit": "m³"},
  "HCPV": {"label": "Hydro carbon pore volume", "unit": "m³"},
  "STOIIP": {"label": "Stock tank oil initially in place", "unit": "Sm³", "eclsum": ["FOIPL", "ROIPL"]},
  "GIIP": {"label": "Gas initially in place", "unit": "Sm³", "eclsum": ["FGIPL", "RGIPL"]},
  "PORO": {"label": "Porosity"},
  "SW": {"label": "Water saturation"},
  "NTG": {"label": "Net to gross"},
  "BO": {"label": "Oil formation volume factor"},
  "BG": {"label": "Gas formation volume factor"}
}
``
